### ISSUE TITLE
Garbage collection

### ISSUE THREAD

**Issue by dthpto** [sepehr/ci-mongodb-session#1]
There remains a lot of garbage after the bots (google etc). Are not automatically removed (more than 12 hours after the  session expires).

**Comment by sepehr** [comment]
Thank you for the report, 
I'll check and see how can I fix the garbage collection method later today.

**Comment by dthpto** [comment]
I found a bug (or feature) in the function _sess_gc() - if the mongo_db driver is used , only one expired record is deleted.
Replacing the $this->mongo_db->delete() on $this->mongo_db->delete_all() - all garbage was deleted, but i don't test direct db access.
// sorry for my bad english

**Comment by sepehr** [comment]
I couldn't find the time to look into the problem but I'm going to ;)
Thank you Alexander.

**Comment by sepehr** [comment]
You were right, I pushed the fix. thank you ;)
